Update rocky_linux_8_optimized_gcp_arm64.cfg to use python 39 instead of 38 (#2505)
gsutil help
WARNING:  Python 3.8 will be deprecated on July 15th, 2025. Please use Python version 3.9 and up.

If you have a compatible Python interpreter installed, you can use it by setting
the CLOUDSDK_PYTHON environment variable to point to it.

Error: gsutil requires Python version 3.9-3.13, but a different version is installed.
You are currently running Python 3.8
Follow the steps below to resolve this issue:
	1. Switch to Python 3.9-3.13 using your Python version manager or install an appropriate version.
	2. If you are unsure how to manage Python versions, visit [https://cloud.google.com/storage/docs/gsutil_install#specifications] for detailed instructions.